[2024-03-18T06:41:06.587+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_separate_groups.delete_dataset_files_0_task scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-03-18T06:41:06.678+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_separate_groups.delete_dataset_files_0_task scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-03-18T06:41:06.688+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-18T06:41:06.833+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): delete_dataset_files_0_task> on 2024-03-17 00:00:00+00:00
[2024-03-18T06:41:06.871+0000] {standard_task_runner.py:60} INFO - Started process 237 to run task
[2024-03-18T06:41:06.927+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'two_separate_groups', 'delete_dataset_files_0_task', 'scheduled__2024-03-17T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_to_gcs.py', '--cfg-path', '/tmp/tmp7lwj11as']
[2024-03-18T06:41:06.951+0000] {standard_task_runner.py:88} INFO - Job 202: Subtask delete_dataset_files_0_task
[2024-03-18T06:41:07.453+0000] {task_command.py:423} INFO - Running <TaskInstance: two_separate_groups.delete_dataset_files_0_task scheduled__2024-03-17T00:00:00+00:00 [running]> on host 9958f290dc4a
[2024-03-18T06:41:08.224+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_separate_groups' AIRFLOW_CTX_TASK_ID='delete_dataset_files_0_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T00:00:00+00:00'
[2024-03-18T06:41:08.237+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-18T06:41:08.292+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm /opt/***/chicago_crime_data_0.csv             rm /opt/***/chicago_crime_data_0.parquet']
[2024-03-18T06:41:08.503+0000] {subprocess.py:86} INFO - Output:
[2024-03-18T06:41:08.563+0000] {subprocess.py:93} INFO - rm: cannot remove 'rm': No such file or directory
[2024-03-18T06:41:08.564+0000] {subprocess.py:93} INFO - rm: cannot remove '/opt/***/chicago_crime_data_0.parquet': No such file or directory
[2024-03-18T06:41:08.565+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-18T06:41:08.587+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-18T06:41:08.627+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=two_separate_groups, task_id=delete_dataset_files_0_task, execution_date=20240317T000000, start_date=20240318T064106, end_date=20240318T064108
[2024-03-18T06:41:08.796+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 202 for task delete_dataset_files_0_task (Bash command failed. The command returned a non-zero exit code 1.; 237)
[2024-03-18T06:41:09.080+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-18T06:41:09.419+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
