[2024-03-28T07:33:11.145+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingesting_data_bq.format_to_parquet_CommArea_task scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-28T07:33:11.184+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingesting_data_bq.format_to_parquet_CommArea_task scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-28T07:33:11.185+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-28T07:33:11.252+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): format_to_parquet_CommArea_task> on 2024-03-27 00:00:00+00:00
[2024-03-28T07:33:11.282+0000] {standard_task_runner.py:60} INFO - Started process 236 to run task
[2024-03-28T07:33:11.285+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingesting_data_bq', 'format_to_parquet_CommArea_task', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_to_gcs.py', '--cfg-path', '/tmp/tmpf8j0mcvt']
[2024-03-28T07:33:11.293+0000] {standard_task_runner.py:88} INFO - Job 399: Subtask format_to_parquet_CommArea_task
[2024-03-28T07:33:11.582+0000] {task_command.py:423} INFO - Running <TaskInstance: ingesting_data_bq.format_to_parquet_CommArea_task scheduled__2024-03-27T00:00:00+00:00 [running]> on host d3d7fa608a49
[2024-03-28T07:33:11.799+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingesting_data_bq' AIRFLOW_CTX_TASK_ID='format_to_parquet_CommArea_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-03-28T07:33:11.803+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_to_gcs.py", line 37, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 1261, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1270, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Empty CSV file
[2024-03-28T07:33:11.819+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=ingesting_data_bq, task_id=format_to_parquet_CommArea_task, execution_date=20240327T000000, start_date=20240328T073311, end_date=20240328T073311
[2024-03-28T07:33:11.836+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 399 for task format_to_parquet_CommArea_task (Empty CSV file; 236)
[2024-03-28T07:33:11.870+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-28T07:33:11.923+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
