[2024-03-12T11:56:02.431+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_separate_groups.wget_dataset_1 manual__2024-03-12T10:11:12.059013+00:00 [queued]>
[2024-03-12T11:56:02.488+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_separate_groups.wget_dataset_1 manual__2024-03-12T10:11:12.059013+00:00 [queued]>
[2024-03-12T11:56:02.489+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-12T11:56:02.604+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): wget_dataset_1> on 2024-03-12 10:11:12.059013+00:00
[2024-03-12T11:56:02.622+0000] {standard_task_runner.py:60} INFO - Started process 1700 to run task
[2024-03-12T11:56:02.646+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'two_separate_groups', 'wget_dataset_1', 'manual__2024-03-12T10:11:12.059013+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/create_dag.py', '--cfg-path', '/tmp/tmp7mt8w4ty']
[2024-03-12T11:56:02.662+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask wget_dataset_1
[2024-03-12T11:56:03.005+0000] {task_command.py:423} INFO - Running <TaskInstance: two_separate_groups.wget_dataset_1 manual__2024-03-12T10:11:12.059013+00:00 [running]> on host 9958f290dc4a
[2024-03-12T11:56:03.446+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_separate_groups' AIRFLOW_CTX_TASK_ID='wget_dataset_1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T10:11:12.059013+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-12T10:11:12.059013+00:00'
[2024-03-12T11:56:03.456+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-12T11:56:03.457+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -O /opt/***/chicago_crime/data.csv https://data.cityofchicago.org/resource/d62x-nvdr.csv?\\$limit=300000']
[2024-03-12T11:56:03.497+0000] {subprocess.py:86} INFO - Output:
[2024-03-12T11:56:03.505+0000] {subprocess.py:93} INFO - /opt/***/chicago_crime/data.csv: No such file or directory
[2024-03-12T11:56:03.505+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-12T11:56:03.531+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-12T11:56:03.541+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=two_separate_groups, task_id=wget_dataset_1, execution_date=20240312T101112, start_date=20240312T115602, end_date=20240312T115603
[2024-03-12T11:56:03.589+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 40 for task wget_dataset_1 (Bash command failed. The command returned a non-zero exit code 1.; 1700)
[2024-03-12T11:56:03.661+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T11:56:03.762+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
