[2024-03-27T14:59:41.245+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T14:59:41.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T14:59:41.257+0000] {logging_mixin.py:188} INFO - [2024-03-27T14:59:41.257+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T14:59:41.270+0000] {logging_mixin.py:188} INFO - [2024-03-27T14:59:41.267+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T14:59:41.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T14:59:41.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.384 seconds
[2024-03-27T15:00:12.968+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:00:12.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:00:12.976+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:00:12.975+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:00:13.009+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:00:12.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:00:13.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:00:13.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.073 seconds
[2024-03-27T15:00:43.718+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:00:43.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:00:43.719+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:00:43.719+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:00:43.735+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:00:43.729+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:00:43.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:00:43.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.049 seconds
[2024-03-27T15:01:13.960+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:01:13.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:01:13.975+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:01:13.975+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:01:13.993+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:01:13.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:01:13.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:01:14.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.065 seconds
[2024-03-27T15:01:44.261+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:01:44.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:01:44.262+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:01:44.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:01:44.275+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:01:44.272+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:01:44.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:01:44.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.036 seconds
[2024-03-27T15:02:14.538+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:02:14.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:02:14.539+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:02:14.539+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:02:14.551+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:02:14.548+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:02:14.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:02:14.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.044 seconds
[2024-03-27T15:02:44.725+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:02:44.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:02:44.728+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:02:44.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:02:44.747+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:02:44.742+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:02:44.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:02:44.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.069 seconds
[2024-03-27T15:03:15.141+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:03:15.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:03:15.143+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:03:15.143+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:03:15.165+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:03:15.156+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:03:15.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:03:15.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.053 seconds
[2024-03-27T15:03:45.661+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:03:45.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:03:45.664+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:03:45.664+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:03:45.675+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:03:45.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:03:45.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:03:45.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.035 seconds
[2024-03-27T15:04:16.074+0000] {processor.py:161} INFO - Started process (PID=545) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:04:16.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:04:16.077+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:04:16.077+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:04:16.095+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:04:16.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:04:16.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:04:16.121+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.050 seconds
[2024-03-27T15:04:46.673+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:04:46.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:04:46.675+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:04:46.675+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:04:46.692+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:04:46.688+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:04:46.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:04:46.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.057 seconds
[2024-03-27T15:05:17.061+0000] {processor.py:161} INFO - Started process (PID=657) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:05:17.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:05:17.072+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:05:17.072+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:05:17.089+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:05:17.085+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:05:17.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:05:17.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.062 seconds
[2024-03-27T15:05:47.328+0000] {processor.py:161} INFO - Started process (PID=714) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:05:47.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:05:47.330+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:05:47.329+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:05:47.340+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:05:47.337+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:05:47.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:05:47.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.052 seconds
[2024-03-27T15:06:17.646+0000] {processor.py:161} INFO - Started process (PID=770) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:06:17.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:06:17.648+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:06:17.648+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:06:17.659+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:06:17.656+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:06:17.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:06:17.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.039 seconds
[2024-03-27T15:06:47.861+0000] {processor.py:161} INFO - Started process (PID=827) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:06:47.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:06:47.863+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:06:47.863+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:06:47.877+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:06:47.873+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:06:47.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:06:47.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.043 seconds
[2024-03-27T15:07:17.972+0000] {processor.py:161} INFO - Started process (PID=883) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:07:17.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:07:17.973+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:07:17.973+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:07:17.985+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:07:17.981+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:07:17.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:07:18.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:07:48.381+0000] {processor.py:161} INFO - Started process (PID=939) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:07:48.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:07:48.383+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:07:48.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:07:48.407+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:07:48.402+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:07:48.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:07:48.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.051 seconds
[2024-03-27T15:08:19.103+0000] {processor.py:161} INFO - Started process (PID=995) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:08:19.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:08:19.106+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:08:19.105+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:08:19.127+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:08:19.122+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:08:19.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:08:19.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.046 seconds
[2024-03-27T15:08:49.295+0000] {processor.py:161} INFO - Started process (PID=1057) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:08:49.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:08:49.297+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:08:49.297+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:08:49.313+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:08:49.308+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:08:49.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:08:49.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.041 seconds
[2024-03-27T15:09:19.455+0000] {processor.py:161} INFO - Started process (PID=1113) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:09:19.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:09:19.462+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:09:19.462+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:09:19.483+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:09:19.479+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:09:19.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:09:19.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.056 seconds
[2024-03-27T15:09:49.897+0000] {processor.py:161} INFO - Started process (PID=1169) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:09:49.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:09:49.898+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:09:49.898+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:09:49.911+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:09:49.906+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:09:49.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:09:49.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.035 seconds
[2024-03-27T15:10:20.058+0000] {processor.py:161} INFO - Started process (PID=1226) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:10:20.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:10:20.060+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:10:20.060+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:10:20.071+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:10:20.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:10:20.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:10:20.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.036 seconds
[2024-03-27T15:10:50.449+0000] {processor.py:161} INFO - Started process (PID=1283) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:10:50.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:10:50.451+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:10:50.450+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:10:50.468+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:10:50.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:10:50.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:10:50.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.041 seconds
[2024-03-27T15:11:20.713+0000] {processor.py:161} INFO - Started process (PID=1339) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:11:20.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:11:20.714+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:11:20.714+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:11:20.728+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:11:20.725+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:11:20.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:11:20.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:11:51.057+0000] {processor.py:161} INFO - Started process (PID=1397) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:11:51.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:11:51.059+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:11:51.059+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:11:51.074+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:11:51.068+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:11:51.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:11:51.094+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.040 seconds
[2024-03-27T15:12:21.217+0000] {processor.py:161} INFO - Started process (PID=1453) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:12:21.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:12:21.220+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:12:21.220+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:12:21.235+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:12:21.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:12:21.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:12:21.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:12:51.297+0000] {processor.py:161} INFO - Started process (PID=1510) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:12:51.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:12:51.326+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:12:51.325+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:12:51.341+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:12:51.338+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:12:51.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:12:51.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.068 seconds
[2024-03-27T15:13:21.580+0000] {processor.py:161} INFO - Started process (PID=1566) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:13:21.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:13:21.582+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:13:21.581+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:13:21.594+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:13:21.591+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:13:21.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:13:21.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.038 seconds
[2024-03-27T15:13:52.151+0000] {processor.py:161} INFO - Started process (PID=1623) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:13:52.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:13:52.153+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:13:52.153+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:13:52.234+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:13:52.230+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:13:52.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:13:52.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.106 seconds
[2024-03-27T15:14:22.348+0000] {processor.py:161} INFO - Started process (PID=1678) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:14:22.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:14:22.350+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:14:22.349+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:14:22.360+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:14:22.357+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:14:22.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:14:22.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:14:52.673+0000] {processor.py:161} INFO - Started process (PID=1734) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:14:52.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:14:52.674+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:14:52.674+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:14:52.684+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:14:52.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:14:52.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:14:52.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:15:23.401+0000] {processor.py:161} INFO - Started process (PID=1790) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:15:23.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:15:23.402+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:15:23.402+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:15:23.413+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:15:23.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:15:23.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:15:23.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:15:53.871+0000] {processor.py:161} INFO - Started process (PID=1846) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:15:53.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:15:53.873+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:15:53.873+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:15:53.883+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:15:53.880+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:15:53.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:15:53.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:16:24.343+0000] {processor.py:161} INFO - Started process (PID=1902) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:16:24.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:16:24.344+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:16:24.344+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:16:24.356+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:16:24.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:16:24.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:16:24.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.034 seconds
[2024-03-27T15:16:54.844+0000] {processor.py:161} INFO - Started process (PID=1958) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:16:54.845+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:16:54.846+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:16:54.846+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:16:54.857+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:16:54.853+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:16:54.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:16:54.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:17:25.339+0000] {processor.py:161} INFO - Started process (PID=2014) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:17:25.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:17:25.341+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:17:25.340+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:17:25.351+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:17:25.349+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:17:25.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:17:25.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:17:55.827+0000] {processor.py:161} INFO - Started process (PID=2070) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:17:55.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:17:55.829+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:17:55.828+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:17:55.842+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:17:55.839+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:17:55.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:17:55.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.036 seconds
[2024-03-27T15:18:25.945+0000] {processor.py:161} INFO - Started process (PID=2126) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:18:25.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:18:25.947+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:18:25.946+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:18:25.959+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:18:25.956+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:18:25.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:18:25.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:18:56.577+0000] {processor.py:161} INFO - Started process (PID=2182) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:18:56.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:18:56.579+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:18:56.578+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:18:56.589+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:18:56.586+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:18:56.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:18:56.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:19:26.659+0000] {processor.py:161} INFO - Started process (PID=2238) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:19:26.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:19:26.661+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:19:26.661+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:19:26.677+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:19:26.674+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:19:26.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:19:26.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.040 seconds
[2024-03-27T15:19:56.971+0000] {processor.py:161} INFO - Started process (PID=2295) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:19:56.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:19:56.973+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:19:56.972+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:19:56.988+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:19:56.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:19:56.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:19:57.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.041 seconds
[2024-03-27T15:20:27.783+0000] {processor.py:161} INFO - Started process (PID=2351) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:20:27.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:20:27.786+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:20:27.785+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:20:27.875+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:20:27.870+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:20:27.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:20:27.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.129 seconds
[2024-03-27T15:20:58.244+0000] {processor.py:161} INFO - Started process (PID=2407) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:20:58.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:20:58.245+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:20:58.245+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:20:58.256+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:20:58.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:20:58.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:20:58.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:21:28.386+0000] {processor.py:161} INFO - Started process (PID=2463) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:21:28.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:21:28.388+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:21:28.388+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:21:28.401+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:21:28.398+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:21:28.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:21:28.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.048 seconds
[2024-03-27T15:21:58.629+0000] {processor.py:161} INFO - Started process (PID=2519) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:21:58.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:21:58.630+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:21:58.630+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:21:58.642+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:21:58.639+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:21:58.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:21:58.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:22:29.215+0000] {processor.py:161} INFO - Started process (PID=2575) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:22:29.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:22:29.217+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:22:29.217+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:22:29.232+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:22:29.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:22:29.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:22:29.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.039 seconds
[2024-03-27T15:22:59.986+0000] {processor.py:161} INFO - Started process (PID=2631) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:22:59.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:22:59.987+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:22:59.987+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:22:59.998+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:22:59.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:22:59.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:23:00.014+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:23:30.767+0000] {processor.py:161} INFO - Started process (PID=2687) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:23:30.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:23:30.769+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:23:30.769+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:23:30.781+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:23:30.778+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:23:30.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:23:30.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:24:01.366+0000] {processor.py:161} INFO - Started process (PID=2743) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:24:01.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:24:01.368+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:24:01.368+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:24:01.378+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:24:01.376+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:24:01.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:24:01.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:24:32.167+0000] {processor.py:161} INFO - Started process (PID=2799) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:24:32.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:24:32.169+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:24:32.169+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:24:32.184+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:24:32.181+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:24:32.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:24:32.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.039 seconds
[2024-03-27T15:25:02.848+0000] {processor.py:161} INFO - Started process (PID=2855) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:25:02.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:25:02.850+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:25:02.849+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:25:02.864+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:25:02.861+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:25:02.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:25:02.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.035 seconds
[2024-03-27T15:25:33.331+0000] {processor.py:161} INFO - Started process (PID=2911) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:25:33.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:25:33.333+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:25:33.332+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:25:33.344+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:25:33.341+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:25:33.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:25:33.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:26:04.036+0000] {processor.py:161} INFO - Started process (PID=2967) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:26:04.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:26:04.038+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:26:04.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:26:04.057+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:26:04.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:26:04.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:26:04.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.049 seconds
[2024-03-27T15:26:34.843+0000] {processor.py:161} INFO - Started process (PID=3023) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:26:34.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:26:34.845+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:26:34.845+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:26:34.859+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:26:34.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:26:34.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:26:34.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:27:05.444+0000] {processor.py:161} INFO - Started process (PID=3079) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:27:05.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:27:05.445+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:27:05.445+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:27:05.456+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:27:05.454+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:27:05.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:27:05.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:27:36.154+0000] {processor.py:161} INFO - Started process (PID=3135) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:27:36.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:27:36.156+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:27:36.156+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:27:36.170+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:27:36.167+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:27:36.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:27:36.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.036 seconds
[2024-03-27T15:28:06.743+0000] {processor.py:161} INFO - Started process (PID=3191) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:28:06.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:28:06.745+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:28:06.745+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:28:06.757+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:28:06.754+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:28:06.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:28:06.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:28:37.403+0000] {processor.py:161} INFO - Started process (PID=3247) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:28:37.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:28:37.405+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:28:37.405+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:28:37.418+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:28:37.414+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:28:37.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:28:37.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:29:08.073+0000] {processor.py:161} INFO - Started process (PID=3304) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:29:08.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:29:08.074+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:29:08.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:29:08.085+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:29:08.083+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:29:08.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:29:08.101+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:29:38.886+0000] {processor.py:161} INFO - Started process (PID=3360) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:29:38.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:29:38.888+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:29:38.888+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:29:38.903+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:29:38.899+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:29:38.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:29:38.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:30:09.129+0000] {processor.py:161} INFO - Started process (PID=3417) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:30:09.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:30:09.131+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:30:09.130+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:30:09.146+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:30:09.142+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:30:09.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:30:09.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:30:39.967+0000] {processor.py:161} INFO - Started process (PID=3473) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:30:39.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:30:39.969+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:30:39.968+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:30:39.978+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:30:39.976+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:30:39.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:30:39.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:31:10.173+0000] {processor.py:161} INFO - Started process (PID=3529) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:31:10.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:31:10.175+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:31:10.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:31:10.190+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:31:10.187+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:31:10.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:31:10.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.068 seconds
[2024-03-27T15:31:40.266+0000] {processor.py:161} INFO - Started process (PID=3585) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:31:40.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:31:40.268+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:31:40.268+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:31:40.278+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:31:40.275+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:31:40.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:31:40.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:32:10.433+0000] {processor.py:161} INFO - Started process (PID=3641) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:32:10.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:32:10.435+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:32:10.435+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:32:10.448+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:32:10.445+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:32:10.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:32:10.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:32:40.590+0000] {processor.py:161} INFO - Started process (PID=3697) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:32:40.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:32:40.591+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:32:40.591+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:32:40.602+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:32:40.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:32:40.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:32:40.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:33:10.758+0000] {processor.py:161} INFO - Started process (PID=3753) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:33:10.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:33:10.759+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:33:10.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:33:10.769+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:33:10.767+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:33:10.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:33:10.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:33:41.561+0000] {processor.py:161} INFO - Started process (PID=3809) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:33:41.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:33:41.563+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:33:41.563+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:33:41.574+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:33:41.571+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:33:41.575+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:33:41.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:34:12.301+0000] {processor.py:161} INFO - Started process (PID=3865) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:34:12.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:34:12.303+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:34:12.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:34:12.319+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:34:12.315+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:34:12.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:34:12.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.038 seconds
[2024-03-27T15:34:42.992+0000] {processor.py:161} INFO - Started process (PID=3921) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:34:42.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:34:42.994+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:34:42.994+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:34:43.006+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:34:43.003+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:34:43.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:34:43.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:35:13.657+0000] {processor.py:161} INFO - Started process (PID=3977) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:35:13.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:35:13.659+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:35:13.659+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:35:13.671+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:35:13.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:35:13.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:35:13.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:35:44.201+0000] {processor.py:161} INFO - Started process (PID=4033) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:35:44.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:35:44.202+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:35:44.202+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:35:44.215+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:35:44.212+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:35:44.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:35:44.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:36:14.412+0000] {processor.py:161} INFO - Started process (PID=4090) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:36:14.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:36:14.414+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:36:14.414+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:36:14.431+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:36:14.426+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:36:14.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:36:14.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.040 seconds
[2024-03-27T15:36:44.500+0000] {processor.py:161} INFO - Started process (PID=4146) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:36:44.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:36:44.501+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:36:44.501+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:36:44.514+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:36:44.511+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:36:44.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:36:44.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.034 seconds
[2024-03-27T15:37:15.019+0000] {processor.py:161} INFO - Started process (PID=4202) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:37:15.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:37:15.021+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:37:15.021+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:37:15.031+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:37:15.029+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:37:15.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:37:15.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:37:45.478+0000] {processor.py:161} INFO - Started process (PID=4258) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:37:45.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:37:45.480+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:37:45.480+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:37:45.491+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:37:45.488+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:37:45.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:37:45.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.035 seconds
[2024-03-27T15:38:16.012+0000] {processor.py:161} INFO - Started process (PID=4314) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:38:16.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:38:16.014+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:38:16.013+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:38:16.024+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:38:16.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:38:16.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:38:16.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:38:46.364+0000] {processor.py:161} INFO - Started process (PID=4370) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:38:46.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:38:46.366+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:38:46.366+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:38:46.379+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:38:46.376+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:38:46.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:38:46.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.034 seconds
[2024-03-27T15:39:17.048+0000] {processor.py:161} INFO - Started process (PID=4425) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:39:17.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:39:17.050+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:39:17.050+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:39:17.063+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:39:17.060+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:39:17.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:39:17.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:39:47.821+0000] {processor.py:161} INFO - Started process (PID=4480) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:39:47.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:39:47.822+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:39:47.822+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:39:47.835+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:39:47.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:39:47.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:39:47.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.034 seconds
[2024-03-27T15:40:18.451+0000] {processor.py:161} INFO - Started process (PID=4537) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:40:18.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:40:18.453+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:40:18.453+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:40:18.463+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:40:18.461+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:40:18.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:40:18.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:40:49.225+0000] {processor.py:161} INFO - Started process (PID=4593) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:40:49.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:40:49.227+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:40:49.227+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:40:49.243+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:40:49.239+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:40:49.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:40:49.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.041 seconds
[2024-03-27T15:41:19.836+0000] {processor.py:161} INFO - Started process (PID=4649) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:41:19.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:41:19.838+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:41:19.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:41:19.851+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:41:19.848+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:41:19.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:41:19.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:41:50.383+0000] {processor.py:161} INFO - Started process (PID=4706) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:41:50.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:41:50.385+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:41:50.385+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:41:50.399+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:41:50.396+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:41:50.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:41:50.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.034 seconds
[2024-03-27T15:42:20.851+0000] {processor.py:161} INFO - Started process (PID=4762) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:42:20.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:42:20.853+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:42:20.853+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:42:20.865+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:42:20.862+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:42:20.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:42:20.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:42:51.332+0000] {processor.py:161} INFO - Started process (PID=4819) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:42:51.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:42:51.333+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:42:51.333+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:42:51.344+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:42:51.341+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:42:51.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:42:51.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:43:21.925+0000] {processor.py:161} INFO - Started process (PID=4881) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:43:21.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:43:21.926+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:43:21.926+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:43:21.939+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:43:21.936+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:43:21.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:43:21.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.055 seconds
[2024-03-27T15:43:52.595+0000] {processor.py:161} INFO - Started process (PID=4937) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:43:52.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:43:52.597+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:43:52.597+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:43:52.607+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:43:52.605+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:43:52.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:43:52.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:44:23.110+0000] {processor.py:161} INFO - Started process (PID=4994) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:44:23.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:44:23.112+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:44:23.111+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:44:23.123+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:44:23.120+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:44:23.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:44:23.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:44:53.757+0000] {processor.py:161} INFO - Started process (PID=5050) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:44:53.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:44:53.759+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:44:53.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:44:53.768+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:44:53.766+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:44:53.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:44:53.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T15:45:24.253+0000] {processor.py:161} INFO - Started process (PID=5106) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:45:24.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:45:24.255+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:45:24.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:45:24.269+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:45:24.266+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:45:24.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:45:24.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:45:54.896+0000] {processor.py:161} INFO - Started process (PID=5162) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:45:54.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:45:54.897+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:45:54.897+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:45:54.909+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:45:54.907+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:45:54.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:45:54.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:46:25.386+0000] {processor.py:161} INFO - Started process (PID=5219) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:46:25.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:46:25.388+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:46:25.388+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:46:25.404+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:46:25.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:46:25.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:46:25.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:46:55.947+0000] {processor.py:161} INFO - Started process (PID=5276) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:46:55.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:46:55.948+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:46:55.948+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:46:55.960+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:46:55.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:46:55.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:46:55.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:47:26.481+0000] {processor.py:161} INFO - Started process (PID=5332) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:47:26.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:47:26.483+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:47:26.482+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:47:26.493+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:47:26.490+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:47:26.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:47:26.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:47:57.013+0000] {processor.py:161} INFO - Started process (PID=5388) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:47:57.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:47:57.014+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:47:57.014+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:47:57.026+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:47:57.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:47:57.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:47:57.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:48:27.749+0000] {processor.py:161} INFO - Started process (PID=5444) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:48:27.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:48:27.751+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:48:27.751+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:48:27.761+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:48:27.759+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:48:27.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:48:27.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:48:58.310+0000] {processor.py:161} INFO - Started process (PID=5500) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:48:58.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:48:58.311+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:48:58.311+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:48:58.324+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:48:58.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:48:58.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:48:58.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:49:28.811+0000] {processor.py:161} INFO - Started process (PID=5556) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:49:28.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:49:28.812+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:49:28.812+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:49:28.824+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:49:28.822+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:49:28.825+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:49:28.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:49:59.369+0000] {processor.py:161} INFO - Started process (PID=5611) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:49:59.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:49:59.371+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:49:59.370+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:49:59.383+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:49:59.380+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:49:59.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:49:59.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:50:29.462+0000] {processor.py:161} INFO - Started process (PID=5667) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:50:29.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:50:29.464+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:50:29.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:50:29.474+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:50:29.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:50:29.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:50:30.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.895 seconds
[2024-03-27T15:51:01.367+0000] {processor.py:161} INFO - Started process (PID=5723) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:51:01.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:51:01.369+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:51:01.369+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:51:01.382+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:51:01.379+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:51:01.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:51:01.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:51:32.081+0000] {processor.py:161} INFO - Started process (PID=5780) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:51:32.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:51:32.083+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:51:32.082+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:51:32.096+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:51:32.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:51:32.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:51:32.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.034 seconds
[2024-03-27T15:52:02.727+0000] {processor.py:161} INFO - Started process (PID=5836) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:52:02.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:52:02.729+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:52:02.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:52:02.739+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:52:02.737+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:52:02.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:52:02.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T15:52:33.472+0000] {processor.py:161} INFO - Started process (PID=5892) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:52:33.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:52:33.473+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:52:33.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:52:33.484+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:52:33.481+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:52:33.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:52:33.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:53:04.227+0000] {processor.py:161} INFO - Started process (PID=5949) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:53:04.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:53:04.229+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:53:04.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:53:04.240+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:53:04.237+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:53:04.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:53:04.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:53:34.859+0000] {processor.py:161} INFO - Started process (PID=6005) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:53:34.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:53:34.862+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:53:34.861+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:53:34.883+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:53:34.877+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:53:34.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:53:34.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.052 seconds
[2024-03-27T15:54:05.673+0000] {processor.py:161} INFO - Started process (PID=6061) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:54:05.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:54:05.674+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:54:05.674+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:54:05.688+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:54:05.685+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:54:05.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:54:05.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.034 seconds
[2024-03-27T15:54:36.216+0000] {processor.py:161} INFO - Started process (PID=6117) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:54:36.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:54:36.218+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:54:36.218+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:54:36.229+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:54:36.226+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:54:36.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:54:36.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:55:06.816+0000] {processor.py:161} INFO - Started process (PID=6173) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:55:06.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:55:06.818+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:55:06.818+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:55:06.831+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:55:06.828+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:55:06.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:55:06.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:55:37.541+0000] {processor.py:161} INFO - Started process (PID=6229) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:55:37.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:55:37.543+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:55:37.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:55:37.555+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:55:37.552+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:55:37.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:55:37.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.035 seconds
[2024-03-27T15:56:08.120+0000] {processor.py:161} INFO - Started process (PID=6285) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:56:08.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:56:08.122+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:56:08.122+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:56:08.135+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:56:08.131+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:56:08.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:56:08.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:56:38.858+0000] {processor.py:161} INFO - Started process (PID=6341) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:56:38.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:56:38.860+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:56:38.860+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:56:38.873+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:56:38.870+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:56:38.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:56:38.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T15:57:09.410+0000] {processor.py:161} INFO - Started process (PID=6397) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:57:09.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:57:09.411+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:57:09.411+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:57:09.424+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:57:09.421+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:57:09.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:57:09.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.035 seconds
[2024-03-27T15:57:40.002+0000] {processor.py:161} INFO - Started process (PID=6453) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:57:40.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:57:40.004+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:57:40.003+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:57:40.018+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:57:40.014+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:57:40.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:57:40.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.037 seconds
[2024-03-27T15:58:10.727+0000] {processor.py:161} INFO - Started process (PID=6509) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:58:10.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:58:10.728+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:58:10.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:58:10.742+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:58:10.739+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:58:10.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:58:10.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.034 seconds
[2024-03-27T15:58:41.197+0000] {processor.py:161} INFO - Started process (PID=6565) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:58:41.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:58:41.198+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:58:41.198+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:58:41.209+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:58:41.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:58:41.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:58:41.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.031 seconds
[2024-03-27T15:59:11.775+0000] {processor.py:161} INFO - Started process (PID=6621) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:59:11.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:59:11.777+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:59:11.777+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:59:11.792+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:59:11.788+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:59:11.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:59:11.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.038 seconds
[2024-03-27T15:59:42.476+0000] {processor.py:161} INFO - Started process (PID=6677) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T15:59:42.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T15:59:42.478+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:59:42.478+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:59:42.490+0000] {logging_mixin.py:188} INFO - [2024-03-27T15:59:42.487+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T15:59:42.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T15:59:42.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.032 seconds
[2024-03-27T16:00:13.296+0000] {processor.py:161} INFO - Started process (PID=6734) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:00:13.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:00:13.298+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:00:13.297+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:00:13.309+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:00:13.307+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T16:00:13.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:00:13.327+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T16:00:44.024+0000] {processor.py:161} INFO - Started process (PID=6791) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:00:44.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:00:44.025+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:00:44.025+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:00:44.035+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:00:44.033+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T16:00:44.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:00:44.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.030 seconds
[2024-03-27T16:01:14.921+0000] {processor.py:161} INFO - Started process (PID=6848) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:01:14.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:01:14.923+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:01:14.923+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:01:14.937+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:01:14.934+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T16:01:14.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:01:14.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.036 seconds
[2024-03-27T16:01:45.787+0000] {processor.py:161} INFO - Started process (PID=6904) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:01:45.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:01:45.789+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:01:45.789+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:01:45.802+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:01:45.799+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T16:01:45.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:01:45.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.035 seconds
[2024-03-27T16:02:16.680+0000] {processor.py:161} INFO - Started process (PID=6961) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:02:16.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:02:16.682+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:02:16.682+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:02:16.700+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:02:16.695+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T16:02:16.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:02:16.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.041 seconds
[2024-03-27T16:02:47.031+0000] {processor.py:161} INFO - Started process (PID=7017) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:02:47.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:02:47.032+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:02:47.032+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:02:47.045+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:02:47.042+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T16:02:47.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:02:47.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T16:03:17.191+0000] {processor.py:161} INFO - Started process (PID=7073) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:17.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:03:17.193+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:03:17.193+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:17.207+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:03:17.204+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T16:03:17.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:17.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.040 seconds
[2024-03-27T16:03:47.290+0000] {processor.py:161} INFO - Started process (PID=7129) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:47.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:03:47.291+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:03:47.291+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:47.303+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:03:47.300+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_transformation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_transformation.py", line 43, in <module>
    "pyspark_job": {"main_python_file_uri": JOB_FILE_URI},
NameError: name 'JOB_FILE_URI' is not defined
[2024-03-27T16:03:47.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:47.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.033 seconds
[2024-03-27T16:03:56.674+0000] {processor.py:161} INFO - Started process (PID=7163) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:56.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:03:56.676+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:03:56.676+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:56.701+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:03:56.798+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:03:56.798+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:03:56.816+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:03:56.816+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:03:56.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.189 seconds
[2024-03-27T16:04:27.034+0000] {processor.py:161} INFO - Started process (PID=7220) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:04:27.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:04:27.036+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:04:27.036+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:04:27.054+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:04:27.182+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:04:27.182+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:04:27.202+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:04:27.202+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:04:27.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.191 seconds
[2024-03-27T16:04:57.713+0000] {processor.py:161} INFO - Started process (PID=7275) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:04:57.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:04:57.717+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:04:57.716+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:04:57.736+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:04:57.952+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:04:57.952+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:04:57.987+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:04:57.986+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:04:58.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.314 seconds
[2024-03-27T16:05:28.853+0000] {processor.py:161} INFO - Started process (PID=7332) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:05:28.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:05:28.855+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:05:28.855+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:05:28.869+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:05:28.962+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:05:28.962+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:05:28.984+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:05:28.984+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:05:29.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.152 seconds
[2024-03-27T16:05:59.101+0000] {processor.py:161} INFO - Started process (PID=7389) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:05:59.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:05:59.103+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:05:59.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:05:59.120+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:05:59.226+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:05:59.226+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:05:59.249+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:05:59.249+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:05:59.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.182 seconds
[2024-03-27T16:06:29.421+0000] {processor.py:161} INFO - Started process (PID=7445) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:06:29.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:06:29.423+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:06:29.423+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:06:29.439+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:06:29.540+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:06:29.540+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:06:29.562+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:06:29.562+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:06:29.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.173 seconds
[2024-03-27T16:06:59.667+0000] {processor.py:161} INFO - Started process (PID=7502) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:06:59.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:06:59.670+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:06:59.670+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:06:59.684+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:06:59.779+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:06:59.779+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:06:59.797+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:06:59.797+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:06:59.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.151 seconds
[2024-03-27T16:07:29.878+0000] {processor.py:161} INFO - Started process (PID=7556) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:07:29.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:07:29.880+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:07:29.880+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:07:29.902+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:07:30.019+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:07:30.019+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:07:30.039+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:07:30.039+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:07:30.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.187 seconds
[2024-03-27T16:08:00.374+0000] {processor.py:161} INFO - Started process (PID=7612) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:08:00.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:08:00.376+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:08:00.376+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:08:00.392+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:08:00.520+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:08:00.520+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:08:00.546+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:08:00.546+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:08:00.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.213 seconds
[2024-03-27T16:08:30.634+0000] {processor.py:161} INFO - Started process (PID=7668) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:08:30.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:08:30.636+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:08:30.635+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:08:30.654+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:08:30.759+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:08:30.759+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:08:30.778+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:08:30.778+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:08:30.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.166 seconds
[2024-03-27T16:09:00.924+0000] {processor.py:161} INFO - Started process (PID=7726) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:09:00.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:09:00.926+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:09:00.926+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:09:00.941+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:09:01.053+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:09:01.053+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:09:01.071+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:09:01.071+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:09:01.094+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.172 seconds
[2024-03-27T16:09:31.215+0000] {processor.py:161} INFO - Started process (PID=7784) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:09:31.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:09:31.217+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:09:31.217+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:09:31.232+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:09:31.324+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:09:31.324+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:09:31.343+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:09:31.343+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:09:31.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.151 seconds
[2024-03-27T16:10:02.382+0000] {processor.py:161} INFO - Started process (PID=7840) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:10:02.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:10:02.384+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:10:02.384+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:10:02.402+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:10:02.505+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:10:02.505+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:10:02.524+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:10:02.524+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:10:02.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.164 seconds
[2024-03-27T16:10:32.586+0000] {processor.py:161} INFO - Started process (PID=7897) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:10:32.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:10:32.589+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:10:32.588+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:10:32.609+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:10:32.705+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:10:32.705+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:10:32.725+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:10:32.724+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:10:32.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.160 seconds
[2024-03-27T16:11:02.807+0000] {processor.py:161} INFO - Started process (PID=7955) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:11:02.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:11:02.810+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:11:02.809+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:11:02.824+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:11:02.927+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:11:02.926+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:11:02.949+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:11:02.948+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:11:02.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.167 seconds
[2024-03-27T16:11:33.558+0000] {processor.py:161} INFO - Started process (PID=8009) to work on /opt/airflow/dags/data_transformation.py
[2024-03-27T16:11:33.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_transformation.py for tasks to queue
[2024-03-27T16:11:33.560+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:11:33.560+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:11:33.577+0000] {processor.py:840} INFO - DAG(s) 'data_crime_process_dag' retrieved from /opt/airflow/dags/data_transformation.py
[2024-03-27T16:11:33.701+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:11:33.700+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-27T16:11:33.723+0000] {logging_mixin.py:188} INFO - [2024-03-27T16:11:33.723+0000] {dag.py:3834} INFO - Setting next_dagrun for data_crime_process_dag to None, run_after=None
[2024-03-27T16:11:33.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_transformation.py took 0.198 seconds
