[2024-03-28T10:09:54.792+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_crime_process_dag.upload_pyspark_script manual__2024-03-28T10:02:37.059426+00:00 [queued]>
[2024-03-28T10:09:54.804+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_crime_process_dag.upload_pyspark_script manual__2024-03-28T10:02:37.059426+00:00 [queued]>
[2024-03-28T10:09:54.805+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-28T10:09:54.820+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): upload_pyspark_script> on 2024-03-28 10:02:37.059426+00:00
[2024-03-28T10:09:54.828+0000] {standard_task_runner.py:60} INFO - Started process 173 to run task
[2024-03-28T10:09:54.831+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_crime_process_dag', 'upload_pyspark_script', 'manual__2024-03-28T10:02:37.059426+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/data_transformation.py', '--cfg-path', '/tmp/tmpljoqe_xe']
[2024-03-28T10:09:54.834+0000] {standard_task_runner.py:88} INFO - Job 440: Subtask upload_pyspark_script
[2024-03-28T10:09:54.882+0000] {task_command.py:423} INFO - Running <TaskInstance: data_crime_process_dag.upload_pyspark_script manual__2024-03-28T10:02:37.059426+00:00 [running]> on host d3d7fa608a49
[2024-03-28T10:09:54.973+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_crime_process_dag' AIRFLOW_CTX_TASK_ID='upload_pyspark_script' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T10:02:37.059426+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-28T10:02:37.059426+00:00'
[2024-03-28T10:09:54.975+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_to_gcs() missing 1 required positional argument: 'object_name'
[2024-03-28T10:09:54.983+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=data_crime_process_dag, task_id=upload_pyspark_script, execution_date=20240328T100237, start_date=20240328T100954, end_date=20240328T100954
[2024-03-28T10:09:54.999+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 440 for task upload_pyspark_script (upload_to_gcs() missing 1 required positional argument: 'object_name'; 173)
[2024-03-28T10:09:55.007+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-28T10:09:55.032+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
